/// Flutter icons Navicons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Navicons
///      fonts:
///       - asset: fonts/Navicons.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class Navicons {
  Navicons._();

  static const _kFontFam = 'Navicons';
  static const String? _kFontPkg = null;

  static const IconData homenav = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schedulenav = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasknav = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
